/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_reclamation_etudiant (void);
GtkWidget* create_ajouter (void);
GtkWidget* create_modifier (void);
GtkWidget* create_suprimer (void);
GtkWidget* create_reponse (void);
GtkWidget* create_reponse_admin (void);
GtkWidget* create_fenetre_afficher (void);
