/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_reclamation_etudiant (void)
{
  GtkWidget *reclamation_etudiant;
  GtkWidget *fixed1;
  GtkWidget *ZOGbuttonajout;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *ZOGbuttonmodifier;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *ZOGbuttonsuprimer;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *ZOGbuttonreponse;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *ZOGbuttonretour;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;
  GtkWidget *afficher;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label36;

  reclamation_etudiant = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (reclamation_etudiant), _("etudiant"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (reclamation_etudiant), fixed1);

  ZOGbuttonajout = gtk_button_new ();
  gtk_widget_show (ZOGbuttonajout);
  gtk_fixed_put (GTK_FIXED (fixed1), ZOGbuttonajout, 256, 24);
  gtk_widget_set_size_request (ZOGbuttonajout, 136, 56);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ZOGbuttonajout), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("ajouter "));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  ZOGbuttonmodifier = gtk_button_new ();
  gtk_widget_show (ZOGbuttonmodifier);
  gtk_fixed_put (GTK_FIXED (fixed1), ZOGbuttonmodifier, 256, 104);
  gtk_widget_set_size_request (ZOGbuttonmodifier, 136, 56);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (ZOGbuttonmodifier), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  ZOGbuttonsuprimer = gtk_button_new ();
  gtk_widget_show (ZOGbuttonsuprimer);
  gtk_fixed_put (GTK_FIXED (fixed1), ZOGbuttonsuprimer, 256, 184);
  gtk_widget_set_size_request (ZOGbuttonsuprimer, 136, 56);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (ZOGbuttonsuprimer), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("suprimer"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  ZOGbuttonreponse = gtk_button_new ();
  gtk_widget_show (ZOGbuttonreponse);
  gtk_fixed_put (GTK_FIXED (fixed1), ZOGbuttonreponse, 256, 272);
  gtk_widget_set_size_request (ZOGbuttonreponse, 136, 56);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (ZOGbuttonreponse), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("reponse"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  ZOGbuttonretour = gtk_button_new ();
  gtk_widget_show (ZOGbuttonretour);
  gtk_fixed_put (GTK_FIXED (fixed1), ZOGbuttonretour, 48, 392);
  gtk_widget_set_size_request (ZOGbuttonretour, 80, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (ZOGbuttonretour), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  afficher = gtk_button_new ();
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher, 256, 352);
  gtk_widget_set_size_request (afficher, 136, 56);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (afficher), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox18), label36, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ZOGbuttonajout, "clicked",
                    G_CALLBACK (on_ZOGbuttonajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) ZOGbuttonmodifier, "clicked",
                    G_CALLBACK (on_ZOGbuttonmodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) ZOGbuttonsuprimer, "clicked",
                    G_CALLBACK (on_ZOGbuttonsuprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) ZOGbuttonreponse, "clicked",
                    G_CALLBACK (on_ZOGbuttonreponse_clicked),
                    NULL);
  g_signal_connect ((gpointer) ZOGbuttonretour, "clicked",
                    G_CALLBACK (on_ZOGbuttonretour_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (reclamation_etudiant, reclamation_etudiant, "reclamation_etudiant");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, ZOGbuttonajout, "ZOGbuttonajout");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, image1, "image1");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, label1, "label1");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, ZOGbuttonmodifier, "ZOGbuttonmodifier");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, image2, "image2");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, label2, "label2");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, ZOGbuttonsuprimer, "ZOGbuttonsuprimer");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, image3, "image3");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, label3, "label3");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, ZOGbuttonreponse, "ZOGbuttonreponse");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, image5, "image5");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, label5, "label5");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, ZOGbuttonretour, "ZOGbuttonretour");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, image4, "image4");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, label4, "label4");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, image18, "image18");
  GLADE_HOOKUP_OBJECT (reclamation_etudiant, label36, "label36");

  return reclamation_etudiant;
}

GtkWidget*
create_ajouter (void)
{
  GtkWidget *ajouter;
  GtkWidget *fixed2;
  GtkWidget *cin;
  GtkWidget *nom;
  GtkWidget *prenom;
  GtkObject *ZOGspinbuttonjour_adj;
  GtkWidget *ZOGspinbuttonjour;
  GtkObject *ZOGspinbuttonmois_adj;
  GtkWidget *ZOGspinbuttonmois;
  GtkObject *ZOGspinbuttonannee_adj;
  GtkWidget *ZOGspinbuttonannee;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label12;
  GtkWidget *ZOGbuttonretour1;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label13;
  GtkWidget *ZOGbuttonterminer;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label14;
  GtkWidget *texte;
  GtkWidget *combobox_service;

  ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter), _("ajouter"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajouter), fixed2);

  cin = gtk_entry_new ();
  gtk_widget_show (cin);
  gtk_fixed_put (GTK_FIXED (fixed2), cin, 176, 24);
  gtk_widget_set_size_request (cin, 272, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (cin), 8226);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed2), nom, 176, 72);
  gtk_widget_set_size_request (nom, 272, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  prenom = gtk_entry_new ();
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed2), prenom, 176, 120);
  gtk_widget_set_size_request (prenom, 272, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom), 8226);

  ZOGspinbuttonjour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  ZOGspinbuttonjour = gtk_spin_button_new (GTK_ADJUSTMENT (ZOGspinbuttonjour_adj), 1, 0);
  gtk_widget_show (ZOGspinbuttonjour);
  gtk_fixed_put (GTK_FIXED (fixed2), ZOGspinbuttonjour, 176, 168);
  gtk_widget_set_size_request (ZOGspinbuttonjour, 60, 27);

  ZOGspinbuttonmois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  ZOGspinbuttonmois = gtk_spin_button_new (GTK_ADJUSTMENT (ZOGspinbuttonmois_adj), 1, 0);
  gtk_widget_show (ZOGspinbuttonmois);
  gtk_fixed_put (GTK_FIXED (fixed2), ZOGspinbuttonmois, 264, 168);
  gtk_widget_set_size_request (ZOGspinbuttonmois, 60, 27);

  ZOGspinbuttonannee_adj = gtk_adjustment_new (2021, 2021, 2022, 1, 10, 10);
  ZOGspinbuttonannee = gtk_spin_button_new (GTK_ADJUSTMENT (ZOGspinbuttonannee_adj), 1, 0);
  gtk_widget_show (ZOGspinbuttonannee);
  gtk_fixed_put (GTK_FIXED (fixed2), ZOGspinbuttonannee, 352, 168);
  gtk_widget_set_size_request (ZOGspinbuttonannee, 60, 27);

  label6 = gtk_label_new (_("Cin :"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 40, 32);
  gtk_widget_set_size_request (label6, 80, 24);

  label7 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 48, 72);
  gtk_widget_set_size_request (label7, 64, 32);

  label8 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 48, 120);
  gtk_widget_set_size_request (label8, 64, 32);

  label9 = gtk_label_new (_("date :"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 48, 168);
  gtk_widget_set_size_request (label9, 64, 32);

  label10 = gtk_label_new (_("Service :"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 16, 216);
  gtk_widget_set_size_request (label10, 136, 40);

  label12 = gtk_label_new (_("texte de reclamation :"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 128, 296);
  gtk_widget_set_size_request (label12, 160, 32);

  ZOGbuttonretour1 = gtk_button_new ();
  gtk_widget_show (ZOGbuttonretour1);
  gtk_fixed_put (GTK_FIXED (fixed2), ZOGbuttonretour1, 24, 440);
  gtk_widget_set_size_request (ZOGbuttonretour1, 104, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (ZOGbuttonretour1), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox6), label13, FALSE, FALSE, 0);

  ZOGbuttonterminer = gtk_button_new ();
  gtk_widget_show (ZOGbuttonterminer);
  gtk_fixed_put (GTK_FIXED (fixed2), ZOGbuttonterminer, 496, 440);
  gtk_widget_set_size_request (ZOGbuttonterminer, 112, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (ZOGbuttonterminer), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("terminer"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox7), label14, FALSE, FALSE, 0);

  texte = gtk_entry_new ();
  gtk_widget_show (texte);
  gtk_fixed_put (GTK_FIXED (fixed2), texte, 136, 328);
  gtk_widget_set_size_request (texte, 344, 96);
  gtk_entry_set_invisible_char (GTK_ENTRY (texte), 8226);

  combobox_service = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combobox_service);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox_service, 176, 216);
  gtk_widget_set_size_request (combobox_service, 301, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_service), _("Hebergement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_service), _("Restauration"));

  g_signal_connect ((gpointer) ZOGbuttonretour1, "clicked",
                    G_CALLBACK (on_ZOGbuttonretour1_clicked),
                    NULL);
  g_signal_connect ((gpointer) ZOGbuttonterminer, "clicked",
                    G_CALLBACK (on_ZOGbuttonterminer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (ajouter, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajouter, cin, "cin");
  GLADE_HOOKUP_OBJECT (ajouter, nom, "nom");
  GLADE_HOOKUP_OBJECT (ajouter, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (ajouter, ZOGspinbuttonjour, "ZOGspinbuttonjour");
  GLADE_HOOKUP_OBJECT (ajouter, ZOGspinbuttonmois, "ZOGspinbuttonmois");
  GLADE_HOOKUP_OBJECT (ajouter, ZOGspinbuttonannee, "ZOGspinbuttonannee");
  GLADE_HOOKUP_OBJECT (ajouter, label6, "label6");
  GLADE_HOOKUP_OBJECT (ajouter, label7, "label7");
  GLADE_HOOKUP_OBJECT (ajouter, label8, "label8");
  GLADE_HOOKUP_OBJECT (ajouter, label9, "label9");
  GLADE_HOOKUP_OBJECT (ajouter, label10, "label10");
  GLADE_HOOKUP_OBJECT (ajouter, label12, "label12");
  GLADE_HOOKUP_OBJECT (ajouter, ZOGbuttonretour1, "ZOGbuttonretour1");
  GLADE_HOOKUP_OBJECT (ajouter, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (ajouter, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (ajouter, image6, "image6");
  GLADE_HOOKUP_OBJECT (ajouter, label13, "label13");
  GLADE_HOOKUP_OBJECT (ajouter, ZOGbuttonterminer, "ZOGbuttonterminer");
  GLADE_HOOKUP_OBJECT (ajouter, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (ajouter, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (ajouter, image7, "image7");
  GLADE_HOOKUP_OBJECT (ajouter, label14, "label14");
  GLADE_HOOKUP_OBJECT (ajouter, texte, "texte");
  GLADE_HOOKUP_OBJECT (ajouter, combobox_service, "combobox_service");

  return ajouter;
}

GtkWidget*
create_modifier (void)
{
  GtkWidget *modifier;
  GtkWidget *fixed3;
  GtkWidget *cinmodif;
  GtkWidget *nommodif;
  GtkWidget *prenommodif;
  GtkObject *ZOGspinbuttonjour1_adj;
  GtkWidget *ZOGspinbuttonjour1;
  GtkObject *ZOGspinbuttonmois1_adj;
  GtkWidget *ZOGspinbuttonmois1;
  GtkObject *ZOGspinbuttonannee1_adj;
  GtkWidget *ZOGspinbuttonannee1;
  GtkWidget *ZOGbuttonchercher;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label23;
  GtkWidget *label19;
  GtkWidget *label15;
  GtkWidget *texte2;
  GtkWidget *ZOGbuttonterminer1;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label24;
  GtkWidget *ZOGbuttonretour2;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label22;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label21;
  GtkWidget *comboboxentry2;

  modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier), _("modifier"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (modifier), fixed3);

  cinmodif = gtk_entry_new ();
  gtk_widget_show (cinmodif);
  gtk_fixed_put (GTK_FIXED (fixed3), cinmodif, 176, 24);
  gtk_widget_set_size_request (cinmodif, 232, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (cinmodif), 8226);

  nommodif = gtk_entry_new ();
  gtk_widget_show (nommodif);
  gtk_fixed_put (GTK_FIXED (fixed3), nommodif, 176, 80);
  gtk_widget_set_size_request (nommodif, 232, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (nommodif), 8226);

  prenommodif = gtk_entry_new ();
  gtk_widget_show (prenommodif);
  gtk_fixed_put (GTK_FIXED (fixed3), prenommodif, 176, 128);
  gtk_widget_set_size_request (prenommodif, 232, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenommodif), 8226);

  ZOGspinbuttonjour1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  ZOGspinbuttonjour1 = gtk_spin_button_new (GTK_ADJUSTMENT (ZOGspinbuttonjour1_adj), 1, 0);
  gtk_widget_show (ZOGspinbuttonjour1);
  gtk_fixed_put (GTK_FIXED (fixed3), ZOGspinbuttonjour1, 176, 176);
  gtk_widget_set_size_request (ZOGspinbuttonjour1, 60, 27);

  ZOGspinbuttonmois1_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  ZOGspinbuttonmois1 = gtk_spin_button_new (GTK_ADJUSTMENT (ZOGspinbuttonmois1_adj), 1, 0);
  gtk_widget_show (ZOGspinbuttonmois1);
  gtk_fixed_put (GTK_FIXED (fixed3), ZOGspinbuttonmois1, 256, 176);
  gtk_widget_set_size_request (ZOGspinbuttonmois1, 60, 27);

  ZOGspinbuttonannee1_adj = gtk_adjustment_new (2021, 2021, 2022, 1, 10, 10);
  ZOGspinbuttonannee1 = gtk_spin_button_new (GTK_ADJUSTMENT (ZOGspinbuttonannee1_adj), 1, 0);
  gtk_widget_show (ZOGspinbuttonannee1);
  gtk_fixed_put (GTK_FIXED (fixed3), ZOGspinbuttonannee1, 336, 176);
  gtk_widget_set_size_request (ZOGspinbuttonannee1, 60, 27);

  ZOGbuttonchercher = gtk_button_new ();
  gtk_widget_show (ZOGbuttonchercher);
  gtk_fixed_put (GTK_FIXED (fixed3), ZOGbuttonchercher, 464, 24);
  gtk_widget_set_size_request (ZOGbuttonchercher, 104, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (ZOGbuttonchercher), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("chercher"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox9), label23, FALSE, FALSE, 0);

  label19 = gtk_label_new (_("Service :"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 56, 232);
  gtk_widget_set_size_request (label19, 49, 17);

  label15 = gtk_label_new (_("Cin :"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 24, 24);
  gtk_widget_set_size_request (label15, 96, 40);

  texte2 = gtk_entry_new ();
  gtk_widget_show (texte2);
  gtk_fixed_put (GTK_FIXED (fixed3), texte2, 120, 352);
  gtk_widget_set_size_request (texte2, 320, 80);
  gtk_entry_set_invisible_char (GTK_ENTRY (texte2), 8226);

  ZOGbuttonterminer1 = gtk_button_new ();
  gtk_widget_show (ZOGbuttonterminer1);
  gtk_fixed_put (GTK_FIXED (fixed3), ZOGbuttonterminer1, 416, 504);
  gtk_widget_set_size_request (ZOGbuttonterminer1, 104, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (ZOGbuttonterminer1), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("terminer"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox10), label24, FALSE, FALSE, 0);

  ZOGbuttonretour2 = gtk_button_new ();
  gtk_widget_show (ZOGbuttonretour2);
  gtk_fixed_put (GTK_FIXED (fixed3), ZOGbuttonretour2, 32, 504);
  gtk_widget_set_size_request (ZOGbuttonretour2, 104, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (ZOGbuttonretour2), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox8), label22, FALSE, FALSE, 0);

  label16 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 48, 88);
  gtk_widget_set_size_request (label16, 56, 24);

  label17 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 48, 136);
  gtk_widget_set_size_request (label17, 72, 24);

  label18 = gtk_label_new (_("Date :"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 48, 184);
  gtk_widget_set_size_request (label18, 56, 24);

  label21 = gtk_label_new (_("texte de reclamation :"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 120, 304);
  gtk_widget_set_size_request (label21, 168, 32);

  comboboxentry2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry2);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxentry2, 176, 224);
  gtk_widget_set_size_request (comboboxentry2, 237, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("Hebergement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("Restauration"));

  g_signal_connect ((gpointer) ZOGbuttonchercher, "clicked",
                    G_CALLBACK (on_ZOGbuttonchercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) ZOGbuttonterminer1, "clicked",
                    G_CALLBACK (on_ZOGbuttonterminer1_clicked),
                    NULL);
  g_signal_connect ((gpointer) ZOGbuttonretour2, "clicked",
                    G_CALLBACK (on_ZOGbuttonretour2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (modifier, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (modifier, cinmodif, "cinmodif");
  GLADE_HOOKUP_OBJECT (modifier, nommodif, "nommodif");
  GLADE_HOOKUP_OBJECT (modifier, prenommodif, "prenommodif");
  GLADE_HOOKUP_OBJECT (modifier, ZOGspinbuttonjour1, "ZOGspinbuttonjour1");
  GLADE_HOOKUP_OBJECT (modifier, ZOGspinbuttonmois1, "ZOGspinbuttonmois1");
  GLADE_HOOKUP_OBJECT (modifier, ZOGspinbuttonannee1, "ZOGspinbuttonannee1");
  GLADE_HOOKUP_OBJECT (modifier, ZOGbuttonchercher, "ZOGbuttonchercher");
  GLADE_HOOKUP_OBJECT (modifier, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (modifier, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (modifier, image9, "image9");
  GLADE_HOOKUP_OBJECT (modifier, label23, "label23");
  GLADE_HOOKUP_OBJECT (modifier, label19, "label19");
  GLADE_HOOKUP_OBJECT (modifier, label15, "label15");
  GLADE_HOOKUP_OBJECT (modifier, texte2, "texte2");
  GLADE_HOOKUP_OBJECT (modifier, ZOGbuttonterminer1, "ZOGbuttonterminer1");
  GLADE_HOOKUP_OBJECT (modifier, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (modifier, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (modifier, image10, "image10");
  GLADE_HOOKUP_OBJECT (modifier, label24, "label24");
  GLADE_HOOKUP_OBJECT (modifier, ZOGbuttonretour2, "ZOGbuttonretour2");
  GLADE_HOOKUP_OBJECT (modifier, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (modifier, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (modifier, image8, "image8");
  GLADE_HOOKUP_OBJECT (modifier, label22, "label22");
  GLADE_HOOKUP_OBJECT (modifier, label16, "label16");
  GLADE_HOOKUP_OBJECT (modifier, label17, "label17");
  GLADE_HOOKUP_OBJECT (modifier, label18, "label18");
  GLADE_HOOKUP_OBJECT (modifier, label21, "label21");
  GLADE_HOOKUP_OBJECT (modifier, comboboxentry2, "comboboxentry2");

  return modifier;
}

GtkWidget*
create_suprimer (void)
{
  GtkWidget *suprimer;
  GtkWidget *fixed4;
  GtkWidget *cinsupp;
  GtkWidget *label25;
  GtkWidget *ZOGbuttonsuprimer1;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label26;

  suprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (suprimer), _("suprimer"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (suprimer), fixed4);

  cinsupp = gtk_entry_new ();
  gtk_widget_show (cinsupp);
  gtk_fixed_put (GTK_FIXED (fixed4), cinsupp, 136, 40);
  gtk_widget_set_size_request (cinsupp, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (cinsupp), 8226);

  label25 = gtk_label_new (_("Cin :"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 24, 40);
  gtk_widget_set_size_request (label25, 88, 40);

  ZOGbuttonsuprimer1 = gtk_button_new ();
  gtk_widget_show (ZOGbuttonsuprimer1);
  gtk_fixed_put (GTK_FIXED (fixed4), ZOGbuttonsuprimer1, 208, 112);
  gtk_widget_set_size_request (ZOGbuttonsuprimer1, 112, 56);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (ZOGbuttonsuprimer1), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("suprimer"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox11), label26, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ZOGbuttonsuprimer1, "clicked",
                    G_CALLBACK (on_ZOGbuttonsuprimer1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (suprimer, suprimer, "suprimer");
  GLADE_HOOKUP_OBJECT (suprimer, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (suprimer, cinsupp, "cinsupp");
  GLADE_HOOKUP_OBJECT (suprimer, label25, "label25");
  GLADE_HOOKUP_OBJECT (suprimer, ZOGbuttonsuprimer1, "ZOGbuttonsuprimer1");
  GLADE_HOOKUP_OBJECT (suprimer, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (suprimer, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (suprimer, image11, "image11");
  GLADE_HOOKUP_OBJECT (suprimer, label26, "label26");

  return suprimer;
}

GtkWidget*
create_reponse (void)
{
  GtkWidget *reponse;
  GtkWidget *fixed5;
  GtkWidget *entry8;
  GtkWidget *label27;
  GtkWidget *hseparator1;
  GtkWidget *hseparator2;
  GtkWidget *studentanswer;
  GtkWidget *ZOGbuttonretour3;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label29;
  GtkWidget *ZOGbuttonokay;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label28;

  reponse = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (reponse), _("reponse"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (reponse), fixed5);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed5), entry8, 136, 40);
  gtk_widget_set_size_request (entry8, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  label27 = gtk_label_new (_("Cin :"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed5), label27, 48, 40);
  gtk_widget_set_size_request (label27, 72, 32);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed5), hseparator1, 16, 104);
  gtk_widget_set_size_request (hseparator1, 456, 24);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (fixed5), hseparator2, 144, 128);
  gtk_widget_set_size_request (hseparator2, 145, 56);

  studentanswer = gtk_label_new ("");
  gtk_widget_show (studentanswer);
  gtk_fixed_put (GTK_FIXED (fixed5), studentanswer, 136, 104);
  gtk_widget_set_size_request (studentanswer, 225, 56);

  ZOGbuttonretour3 = gtk_button_new ();
  gtk_widget_show (ZOGbuttonretour3);
  gtk_fixed_put (GTK_FIXED (fixed5), ZOGbuttonretour3, 48, 208);
  gtk_widget_set_size_request (ZOGbuttonretour3, 96, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (ZOGbuttonretour3), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox13), label29, FALSE, FALSE, 0);

  ZOGbuttonokay = gtk_button_new ();
  gtk_widget_show (ZOGbuttonokay);
  gtk_fixed_put (GTK_FIXED (fixed5), ZOGbuttonokay, 384, 40);
  gtk_widget_set_size_request (ZOGbuttonokay, 80, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (ZOGbuttonokay), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Okay"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox12), label28, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ZOGbuttonretour3, "clicked",
                    G_CALLBACK (on_ZOGbuttonretour3_clicked),
                    NULL);
  g_signal_connect ((gpointer) ZOGbuttonokay, "clicked",
                    G_CALLBACK (on_ZOGbuttonokay_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (reponse, reponse, "reponse");
  GLADE_HOOKUP_OBJECT (reponse, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (reponse, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (reponse, label27, "label27");
  GLADE_HOOKUP_OBJECT (reponse, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (reponse, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (reponse, studentanswer, "studentanswer");
  GLADE_HOOKUP_OBJECT (reponse, ZOGbuttonretour3, "ZOGbuttonretour3");
  GLADE_HOOKUP_OBJECT (reponse, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (reponse, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (reponse, image13, "image13");
  GLADE_HOOKUP_OBJECT (reponse, label29, "label29");
  GLADE_HOOKUP_OBJECT (reponse, ZOGbuttonokay, "ZOGbuttonokay");
  GLADE_HOOKUP_OBJECT (reponse, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (reponse, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (reponse, image12, "image12");
  GLADE_HOOKUP_OBJECT (reponse, label28, "label28");

  return reponse;
}

GtkWidget*
create_reponse_admin (void)
{
  GtkWidget *reponse_admin;
  GtkWidget *fixed6;
  GtkWidget *cinreponse;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *btnRetour;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label33;
  GtkWidget *btnTerminer;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label32;
  GtkWidget *ZOGradiobutton2;
  GSList *ZOGradiobutton2_group = NULL;
  GtkWidget *ZOGradiobutton1;

  reponse_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (reponse_admin), _("Reponse"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (reponse_admin), fixed6);

  cinreponse = gtk_entry_new ();
  gtk_widget_show (cinreponse);
  gtk_fixed_put (GTK_FIXED (fixed6), cinreponse, 256, 32);
  gtk_widget_set_size_request (cinreponse, 168, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (cinreponse), 8226);

  label30 = gtk_label_new (_("Reponse : "));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed6), label30, 96, 88);
  gtk_widget_set_size_request (label30, 105, 33);

  label31 = gtk_label_new (_("CIN :"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed6), label31, 96, 32);
  gtk_widget_set_size_request (label31, 105, 33);

  btnRetour = gtk_button_new ();
  gtk_widget_show (btnRetour);
  gtk_fixed_put (GTK_FIXED (fixed6), btnRetour, 104, 136);
  gtk_widget_set_size_request (btnRetour, 160, 56);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (btnRetour), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox15), label33, FALSE, FALSE, 0);

  btnTerminer = gtk_button_new ();
  gtk_widget_show (btnTerminer);
  gtk_fixed_put (GTK_FIXED (fixed6), btnTerminer, 296, 136);
  gtk_widget_set_size_request (btnTerminer, 144, 56);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (btnTerminer), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Terminer"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox14), label32, FALSE, FALSE, 0);

  ZOGradiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("r\303\251fuser"));
  gtk_widget_show (ZOGradiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed6), ZOGradiobutton2, 392, 96);
  gtk_widget_set_size_request (ZOGradiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ZOGradiobutton2), ZOGradiobutton2_group);
  ZOGradiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ZOGradiobutton2));

  ZOGradiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("accepter"));
  gtk_widget_show (ZOGradiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed6), ZOGradiobutton1, 232, 96);
  gtk_widget_set_size_request (ZOGradiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ZOGradiobutton1), ZOGradiobutton2_group);
  ZOGradiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ZOGradiobutton1));

  g_signal_connect ((gpointer) btnRetour, "clicked",
                    G_CALLBACK (on_btnRetour_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnTerminer, "clicked",
                    G_CALLBACK (on_btnTerminer_clicked),
                    NULL);
  g_signal_connect ((gpointer) ZOGradiobutton2, "toggled",
                    G_CALLBACK (on_ZOGradiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) ZOGradiobutton1, "toggled",
                    G_CALLBACK (on_ZOGradiobutton1_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (reponse_admin, reponse_admin, "reponse_admin");
  GLADE_HOOKUP_OBJECT (reponse_admin, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (reponse_admin, cinreponse, "cinreponse");
  GLADE_HOOKUP_OBJECT (reponse_admin, label30, "label30");
  GLADE_HOOKUP_OBJECT (reponse_admin, label31, "label31");
  GLADE_HOOKUP_OBJECT (reponse_admin, btnRetour, "btnRetour");
  GLADE_HOOKUP_OBJECT (reponse_admin, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (reponse_admin, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (reponse_admin, image15, "image15");
  GLADE_HOOKUP_OBJECT (reponse_admin, label33, "label33");
  GLADE_HOOKUP_OBJECT (reponse_admin, btnTerminer, "btnTerminer");
  GLADE_HOOKUP_OBJECT (reponse_admin, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (reponse_admin, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (reponse_admin, image14, "image14");
  GLADE_HOOKUP_OBJECT (reponse_admin, label32, "label32");
  GLADE_HOOKUP_OBJECT (reponse_admin, ZOGradiobutton2, "ZOGradiobutton2");
  GLADE_HOOKUP_OBJECT (reponse_admin, ZOGradiobutton1, "ZOGradiobutton1");

  return reponse_admin;
}

GtkWidget*
create_fenetre_afficher (void)
{
  GtkWidget *fenetre_afficher;
  GtkWidget *fixed7;
  GtkWidget *ZOGtreeview1;
  GtkWidget *btnReponse;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label35;
  GtkWidget *buttonretour;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label34;
  GtkWidget *ZOGbuttonplus;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label40;
  GtkWidget *labelmsg;

  fenetre_afficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (fenetre_afficher, 1200, 600);
  gtk_window_set_title (GTK_WINDOW (fenetre_afficher), _("affichage"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (fenetre_afficher), fixed7);

  ZOGtreeview1 = gtk_tree_view_new ();
  gtk_widget_show (ZOGtreeview1);
  gtk_fixed_put (GTK_FIXED (fixed7), ZOGtreeview1, 120, 16);
  gtk_widget_set_size_request (ZOGtreeview1, 832, 416);

  btnReponse = gtk_button_new ();
  gtk_widget_show (btnReponse);
  gtk_fixed_put (GTK_FIXED (fixed7), btnReponse, 968, 72);
  gtk_widget_set_size_request (btnReponse, 130, 48);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (btnReponse), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-copy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Repondre"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox17), label35, FALSE, FALSE, 0);

  buttonretour = gtk_button_new ();
  gtk_widget_show (buttonretour);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonretour, 104, 496);
  gtk_widget_set_size_request (buttonretour, 114, 48);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (buttonretour), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox16), label34, FALSE, FALSE, 0);

  ZOGbuttonplus = gtk_button_new ();
  gtk_widget_show (ZOGbuttonplus);
  gtk_fixed_put (GTK_FIXED (fixed7), ZOGbuttonplus, 656, 488);
  gtk_widget_set_size_request (ZOGbuttonplus, 152, 48);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (ZOGbuttonplus), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("le plus r\303\251clamer"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox21), label40, FALSE, FALSE, 0);

  labelmsg = gtk_label_new ("");
  gtk_widget_show (labelmsg);
  gtk_fixed_put (GTK_FIXED (fixed7), labelmsg, 856, 496);
  gtk_widget_set_size_request (labelmsg, 312, 32);

  g_signal_connect ((gpointer) btnReponse, "clicked",
                    G_CALLBACK (on_btnReponse_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretour, "clicked",
                    G_CALLBACK (on_buttonretour_clicked),
                    NULL);
  g_signal_connect ((gpointer) ZOGbuttonplus, "clicked",
                    G_CALLBACK (on_ZOGbuttonplus_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_afficher, fenetre_afficher, "fenetre_afficher");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, ZOGtreeview1, "ZOGtreeview1");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, btnReponse, "btnReponse");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image17, "image17");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label35, "label35");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, buttonretour, "buttonretour");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image16, "image16");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label34, "label34");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, ZOGbuttonplus, "ZOGbuttonplus");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, image21, "image21");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, label40, "label40");
  GLADE_HOOKUP_OBJECT (fenetre_afficher, labelmsg, "labelmsg");

  return fenetre_afficher;
}

